name: Audit

on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked
      - name: cargo deny check
        run: cargo deny check
